version: "3.9"

services:
  llama:
    build:
      context: .
      dockerfile: Dockerfile.llama
    ports:
      - "8080:8080"
    volumes:
      - ./model:/app/model
    environment:
      - MODEL_PATH=/app/model/llama

  pgvector:
    image: ankane/pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
